export type PageId = keyof typeof PAGE_TO_PATH;

export const PAGE_TO_PATH = {
  dashboard: '/dashboard',
  'teacher-dashboard': '/teacher-dashboard',
  students: '/students',
  attendance: '/attendance',
  diary: '/diary',
  exams: '/examinations',
  timetable: '/timetable',
  classes: '/classes',
  fee: '/fee-management',
  'fee-categories': '/fee-categories',
  staff: '/staff',
  'staff-attendance': '/staff-attendance',
  faculty: '/faculty',
  leave: '/leave',
  bus: '/bus-tracking',
  reports: '/reports',
  settings: '/settings',
  whatsapp: '/whatsapp',
  promotion: '/promotion',
  alumni: '/alumni',
  search: '/search',
  salary: '/salary',
  'salary-categories': '/salary-categories',
  expenses: '/expenses',
  substitute: '/substitute',
  'staff-access': '/staff-access',
  meetings: '/parent-meetings',
  'activity-logs': '/activity-logs',
  homework: '/homework',
  'allot-attendance': '/allot-attendance',
  performance: '/performance',
  'my-salary': '/my-salary',
  webhook: '/webhook',
  'recycle-bin': '/recycle-bin',
};
